<?php if($this->isEnabled()): ?>
<script type="text/javascript">
    function addEvent(elem, event, fn) {
        function listenHandler(e) {
            var ret = fn.apply(this, arguments);
            if (ret === false) {
                e.stopPropagation();
                e.preventDefault();
            }
            return(ret);
        }

        function attachHandler() {
            var ret = fn.call(elem, window.event);
            if (ret === false) {
                window.event.returnValue = false;
                window.event.cancelBubble = true;
            }
            return(ret);
        }

        if (elem.addEventListener) {
            elem.addEventListener(event, listenHandler, false);
        } else {
            elem.attachEvent("on" + event, attachHandler);
        }
    }

    var Yuzu = Yuzu || {configure: function(e) {
        this._cf = e
    }, addEvent: function(c, d, a) {
        this._eq = this._eq || [], this._eq.push([c,d,a])
    }, setCustomerId: function(i) {
        this._mp = i
    }, setL10n: function(l10n) {
        this._l10n = l10n
    }};
    (function() {
        var e = document.createElement("script");
        e.type = "text/javascript", e.async = !0, e.src = ("https:" == document.location.protocol ? "https:" : "http:") + "<?php echo Mage::helper('yuzu_tags')->getConfig('yuzu_tags/general/tag_url_js'); ?>";

        var t = document.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(e, t)
    })();
</script>
<?php endif; ?>